#!/bin/sh

export MONTECARLO_PATH=${PWD}

rm -f ${MONTECARLO_PATH}/libMontecarlo.so
cd ${MONTECARLO_PATH}/Sources
c++ -std=c++11 -Wall -fPIC -shared -I. -o ${MONTECARLO_PATH}/libMontecarlo.so *.cc
cd ..
