#!/bin/sh

#export ROOT_LIBS="-L/usr/lib/i386-linux-gnu -lCore -lCint -lRIO -lNet -lHist -lGraf -lGpad -lTree -lRint -lMatrix -lMathCore -lThread -pthread -lm -ldl -rdynamic"
export MONTECARLO_PATH=${PWD}/..
export LD_LIBRARY_PATH=${MONTECARLO_PATH}

export EXEC_NAME=fit_fix_alpha
export MAIN_SOURCE=${EXEC_NAME}.cxx

